name: 'Mirror Branch to Branch'
description: 'Mirror any branch A to any branch B'
inputs:
  source-branch:
    description: 'Branch to mirror from'
    required: true
  target-branch:
    description: 'Branch to mirror to'
    required: false
    default: 'master'
  token:
    description: >
      Token used to access the Github API. You can leave this as the default
      and Github will automatically provision one for you for this action.
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  force:
    description: >
      Whether to force push when updating the target branch.
      true = force push, false = don't force push.
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'index.js'
